### ISSUE TITLE
Looks like runner ignores deafult value of non-required action params

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-actions-act-runner#5]
For example, in my composite action I have:
```
inputs:
  param1:
    description: "my optional param no.1"
    required: false
    default: true
```

Then when the parameter is not mentioned when the action is used, then it's value is not `true`, I suspect it is just blank, but I haven't checked.
